language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements-development.txt
script:
  - py.test --cov=clean_validator tests/
  - pycodestyle clean_validator tests
